[package]
name = "holomidi"
version = "0.0.1"
edition = "2024"

[dependencies]
[target.'cfg(windows)'.dependencies]
midir = "0.8"

[target.'cfg(unix)'.dependencies]
midir = { version = "0.8", features = ["alsa"] }